/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressorasRouteImport } from './routes/impressoras'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as IndexRouteImport } from './routes/index'

const ImpressorasRoute = ImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/importar': typeof ImportarRoute
  '/impressoras': typeof ImpressorasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/importar': typeof ImportarRoute
  '/impressoras': typeof ImpressorasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/importar': typeof ImportarRoute
  '/impressoras': typeof ImpressorasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estoque' | '/importar' | '/impressoras'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estoque' | '/importar' | '/impressoras'
  id: '__root__' | '/' | '/estoque' | '/importar' | '/impressoras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstoqueRoute: typeof EstoqueRoute
  ImportarRoute: typeof ImportarRoute
  ImpressorasRoute: typeof ImpressorasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressoras': {
      id: '/impressoras'
      path: '/impressoras'
      fullPath: '/impressoras'
      preLoaderRoute: typeof ImpressorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstoqueRoute: EstoqueRoute,
  ImportarRoute: ImportarRoute,
  ImpressorasRoute: ImpressorasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
